#!/usr/bin/env bash
CODE_EXTENSIONS_NOT_INSTALLED=$(comm -23 <(cat $HOME/dotfiles/config/VSCode/extensions_list | sort ) <(code --list-extensions | sort))
if [ ! -z "$CODE_EXTENSIONS_NOT_INSTALLED" ]; then
    echo '######## Not installed VSCode extensions (run "cat files/VSCode/extensions_list | xargs -I{} code --install-extension {}" to install them) #########'
    echo "$CODE_EXTENSIONS_NOT_INSTALLED" | xargs -n1 echo " => "
    echo '###############################################################################################'
fi
