---
- name: Check nvm existence
  shell: ls -lh '{{ home_dir }}/.nvm'
  register: nvm_check
  ignore_errors: True
  tags:
    - node

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | zsh
  args:
    creates: "{{ home_dir }}/.nvm/nvm.sh"
  tags:
    - node
