#!/usr/bin/env bash
CODE_EXTENSIONS_NOT_INSTALLED=$(comm -23 <(cat $HOME/dotfiles/files/VSCode/extensions_list | sort ) <(code --list-extensions | sort))
if [ ! -z "$CODE_EXTENSIONS_NOT_INSTALLED" ]; then
    echo '######## Not installed VSCode extensions (run playbook with "-t vscode" to install them) #########'
    echo "$CODE_EXTENSIONS_NOT_INSTALLED" | xargs -n1 echo " => "
    echo '###############################################################################################'
fi
